export const CREATE_CHECKOUT_SESSION = 'activeSubscription/CREATE_CHECKOUT_SESSION';
export const CREATE_ACTIVE_SUBSCRIPTION = 'activeSubscription/CREATE_ACTIVE_SUBSCRIPTION';
export const GET_CURRENT_ACTIVE_SUBSCRIPTION = 'activeSubscription/GET_CURRENT_ACTIVE_SUBSCRIPTION';
